import { Item } from "@/types/Item";
import { Budget } from "@/types/Budget";

export const TEST_ITEMS: Item[] = [
  {
    id: "1",
    family: "Motores",
    subfamily: "Eléctricos",
    detail: "Motor eléctrico",
    brand: "Siemens",
    quantity: 10,
    unit: "Unidades",
    partNumber: "MTR-1234",
    numbering: "P000000001",
  },
  {
    id: "2",
    family: "Hidráulicos",
    subfamily: "Bombas",
    detail: "Bomba hidráulica",
    brand: "Bosch",
    quantity: 5,
    unit: "Unidades",
    partNumber: "BMP-5678",
    numbering: "P000000002",
  },
  {
    id: "3",
    family: "Cables",
    subfamily: "Eléctricos",
    detail: "Cable eléctrico de cobre",
    brand: "General Cable",
    quantity: 100,
    unit: "Metros",
    partNumber: "CBL-2025",
    numbering: "P000000003",
  },
];

export const TEST_BUDGETS: Budget[] = [
  {
    id: "1",
    date: "2025-01-23",
    item: TEST_ITEMS[0].detail,
    origin: "China",
    destination: "Estados Unidos",
    supplier: "Tech Supplier Inc.",
    deliveryTime: 15,
    unitPrice: 100,
    currency: "USD",
    margin: 10,
    totalPrice: 1100,
    unitWeight: 1,
    totalWeight: 10,
    unit: "kg",
    incoterm: "FOB",
    transport: null,
    custom: null,
    delivery: null,
    numbering: "0000000001",
    stage: "COTI",
  },
  {
    id: "2",
    date: "2025-01-22",
    item: TEST_ITEMS[0].detail,
    origin: "Alemania",
    destination: "Estados Unidos",
    supplier: "Auto Parts GmbH",
    deliveryTime: 20,
    unitPrice: 150,
    currency: "EUR",
    margin: 15,
    totalPrice: 1725,
    unitWeight: 2,
    totalWeight: 20,
    unit: "kg",
    incoterm: "CIF",
    transport: null,
    custom: null,
    delivery: null,
    numbering: "0000000002",
    stage: "COTI",
  },
  {
    id: "3",
    date: "2025-01-20",
    item: TEST_ITEMS[1].detail,
    origin: "Vietnam",
    destination: "Australia",
    supplier: "VietFurnish Co.",
    deliveryTime: 25,
    unitPrice: 50,
    currency: "AUD",
    margin: 20,
    totalPrice: 1500,
    unitWeight: 5,
    totalWeight: 75,
    unit: "kg",
    incoterm: "EXW",
    transport: null,
    custom: null,
    delivery: null,
    numbering: "0000000003",
    stage: "COTI",
  },
  {
    id: "B004",
    date: "2025-01-18",
    item: TEST_ITEMS[2].detail,
    origin: "India",
    destination: "Estados Unidos",
    supplier: "Textile World",
    deliveryTime: 12,
    unitPrice: 25,
    currency: "GBP",
    margin: 10,
    totalPrice: 550,
    unitWeight: 0.5,
    totalWeight: 11,
    unit: "kg",
    incoterm: "DAP",
    transport: null,
    custom: null,
    delivery: null,
    numbering: "0000000004",
    stage: "COTI",
  },
  {
    id: "B005",
    date: "2025-01-17",
    item: TEST_ITEMS[0].detail,
    origin: "Suiza",
    destination: "Argentina",
    supplier: "SwissPharma AG",
    deliveryTime: 10,
    unitPrice: 200,
    currency: "CAD",
    margin: 5,
    totalPrice: 2100,
    unitWeight: 0.2,
    totalWeight: 2,
    unit: "kg",
    incoterm: "FCA",
    transport: null,
    custom: null,
    delivery: null,
    numbering: "0000000005",
    stage: "COTI",
  },
];
