import { Item } from "@/types/Item";
import { Budget } from "@/types/Budget";

export const TEST_ITEMS: Item[] = [
  {
    id: 1,
    family: "Motores",
    subfamily: "Eléctricos",
    detail: "Motor eléctrico",
    brand: "Siemens",
    quantity: 10,
    unit: "Unidades",
    partNumber: "MTR-1234",
    numbering: "P000000001",
    model: "Modelo-X1",
    productNumber: "CL-0001",
  },
  {
    id: 2,
    family: "Hidráulicos",
    subfamily: "Bombas",
    detail: "Bomba hidráulica",
    brand: "Bosch",
    quantity: 5,
    unit: "Unidades",
    partNumber: "BMP-5678",
    numbering: "P000000002",
    model: "Modelo-H2",
    productNumber: "CL-0002",
  },
  {
    id: 3,
    family: "Cables",
    subfamily: "Eléctricos",
    detail: "Cable eléctrico de cobre",
    brand: "General Cable",
    quantity: 100,
    unit: "Metros",
    partNumber: "CBL-2025",
    numbering: "P000000003",
    model: "Modelo-C3",
    productNumber: "CL-0003",
  },
];

export const TEST_BUDGETS: Budget[] = [
  {
    numbering: "0000000001",
    purchaseData: {
      date: "2025-01-23",
      item: TEST_ITEMS[0],
      origin: "China",
      destination: "Estados Unidos",
      supplier: "Tech Supplier Inc.",
      currency: "USD",
      unitPrice: 200,
      margin: 0,
      appliedUnitPrice: 200,
      deliveryTime: 15,
      unitWeight: 1,
      totalWeight: 10,
      unit: "kg",
      incoterm: "FOB",
      additionalObservations: "",
    },
    freight: null,
    salesData: {
      unitSalePrice: 0,
      margin: 15,
      totalPrice: 0,
      paymentCondition: "A Convenir",
    },
    stage: "COTI",
  },
  {
    numbering: "0000000002",
    purchaseData: {
      date: "2025-01-22",
      item: TEST_ITEMS[0],
      origin: "Alemania",
      destination: "Estados Unidos",
      supplier: "Auto Parts GmbH",
      currency: "USD",
      unitPrice: 180,
      margin: 0,
      appliedUnitPrice: 100,
      deliveryTime: 20,
      unitWeight: 2,
      totalWeight: 20,
      unit: "kg",
      incoterm: "CIF",
      additionalObservations: "Test",
    },
    freight: null,
    salesData: null,
    stage: "COTI",
  },
  {
    numbering: "0000000003",
    purchaseData: {
      date: "2025-01-20",
      item: TEST_ITEMS[1],
      origin: "Vietnam",
      destination: "Australia",
      supplier: "VietFurnish Co.",
      currency: "USD",
      unitPrice: 150,
      margin: 0,
      appliedUnitPrice: 150,
      deliveryTime: 25,
      unitWeight: 5,
      totalWeight: 75,
      unit: "kg",
      incoterm: "EXW",
      additionalObservations: "",
    },
    freight: null,
    salesData: null,
    stage: "COTI",
  },
  {
    numbering: "0000000004",
    purchaseData: {
      date: "2025-01-18",
      item: TEST_ITEMS[2],
      origin: "India",
      destination: "Estados Unidos",
      supplier: "Textile World",
      currency: "USD",
      unitPrice: 100,
      margin: 0,
      appliedUnitPrice: 100,
      deliveryTime: 12,
      unitWeight: 0.5,
      totalWeight: 11,
      unit: "kg",
      incoterm: "DAP",
      additionalObservations: "",
    },
    freight: null,
    salesData: null,
    stage: "COTI",
  },
  {
    numbering: "0000000005",
    purchaseData: {
      date: "2025-01-17",
      item: TEST_ITEMS[0],
      origin: "Suiza",
      destination: "Argentina",
      supplier: "SwissPharma AG",
      currency: "USD",
      unitPrice: 120,
      margin: 0,
      appliedUnitPrice: 120,
      deliveryTime: 10,
      unitWeight: 0.2,
      totalWeight: 2,
      unit: "kg",
      incoterm: "FCA",
      additionalObservations: "",
    },
    freight: null,
    salesData: null,
    stage: "COTI",
  },
];
